### PR TITLE
draft proposal to restructure chapters

### PR DESCRIPTION
**Pull request by ansuz**
This is a WIP draft of a PR to follow up on [my proposal to split some chapters into smaller sections](https://github.com/webxdc/webxdc_docs/issues/79). I intend to clean it up a little more, but I wanted to validate the overall structure before putting in more effort.

A general overview:

1. the _Webxdc Specification_ describes the spec from the perspectives of both a _webxdc app developer_ (assumed to be a relative novice or hobbyist level of expertise) and a _messaging app developer_ (who I'll refer to as a platform dev) who is considering implementing webxdc support in their client. There is some overlap between the two, which is reasonable, but I think the language differs significantly. The beginner-friendly sections use plain language, while the notes for platform dev read more like an RFC (with terms like **SHOULD**, **MUST**, etc.). I haven't separated these sections yet, but I think it might be worthwhile to do so.

2. The _specification_ section also covered the state of a number of webview APIs as both _DOs_ (`localStorage`, `indexedDB`, `visibilityChange`, etc.) and _DON'Ts_ (`beforeunload`, `document.cookie`, `open`, `alert`, `prompt`). I believe these are more appropriately grouped under _Compatibility_ in the _Tips & Tricks_ section, where there was already a mention of using babeljs to transpile to a portable subset of js.

3. My original intention was to introduce a new section about synchronizing shared state via CRDTs, which would have been too long on its own to simply include into the _Tips and Tricks_ section as it was. In the proposed structure this will get its own page, but for now I only have a placeholder with a very rough content outline.

4. I understand that these sections were originally grouped together with the intent of avoiding very small pages. In its current state there is a `selfAddr_and_selfName` section which is considerably shorter than the others, however, I think it could easily benefit from some additional description. For example, neither API describes the data-type of the id or name. I believe they are strings, but that isn't explicit. It would probably benefit both app and platform developers to describe the behaviour in existing implementations, along with situations where either value might be useful.

That's all for now. I don't think _Intro_, _Get Started_, or _FAQ_ justify being split up. Personally I find it easier to get an overview of the _spec_ and _tips_ section with the sub-headings in the sidebar.

Any thoughts/questions/objections before I proceed further?

### CODE REVIEW

**Comment by hpk42** [comment]
On Sat, Oct 14, 2023 at 06:03 -0700, ansuz wrote:
> This is a WIP draft of a PR to follow up on [my proposal to split some chapters into smaller sections](https://github.com/webxdc/webxdc_docs/issues/79). I intend to clean it up a little more, but I wanted to validate the overall structure before putting in more effort.
> 
> A general overview:
> 
> 1. the _Webxdc Specification_ describes the spec from the perspectives of both a _webxdc app developer_ (assumed to be a relative novice or hobbyist level of expertise) and a _messaging app developer_ (who I&#39;ll refer to as a platform dev) who is considering implementing webxdc support in their client. There is some overlap between the two, which is reasonable, but I think the language differs significantly. The beginner-friendly sections use plain language, while the notes for platform dev read more like an RFC (with terms like **SHOULD**, **MUST**, etc.). I haven&#39;t separated these sections yet, but I think it might be worthwhile to do so.

+1
 
> 2. The _specification_ section also covered the state of a number of webview APIs as both _DOs_ (`localStorage`, `indexedDB`, `visibilityChange`, etc.) and _DON&#39;Ts_ (`beforeunload`, `document.cookie`, `open`, `alert`, `prompt`). I believe these are more appropriately grouped under _Compatibility_ in the _Tips &amp; Tricks_ section, where there was already a mention of using babeljs to transpile to a portable subset of js.

+1
 
> 3. My original intention was to introduce a new section about synchronizing shared state via CRDTs, which would have been too long on its own to simply include into the _Tips and Tricks_ section as it was. In the proposed structure this will get its own page, but for now I only have a placeholder with a very rough content outline.

+1
 
> 4. I understand that these sections were originally grouped together with the intent of avoiding very small pages. In its current state there is a `selfAddr_and_selfName` section which is considerably shorter than the others, however, I think it could easily benefit from some additional description. For example, neither API describes the data-type of the id or name. I believe they are strings, but that isn&#39;t explicit. It would probably benefit both app and platform developers to describe the behaviour in existing implementations, along with situations where either value might be useful.
> 
> That&#39;s all for now. I don&#39;t think _Intro_, _Get Started_, or _FAQ_ justify being split up. Personally I find it easier to get an overview of the _spec_ and _tips_ section with the sub-headings in the sidebar.

yes, sounds good.  Looked at the output. 
Still can't quite believe that having sub-headings in the sidebar requires that sub-headings have their own file instead of mdbook pulling in the subsection titles into the TOC but we
can check that later.  In any case, the new structure is easier to navigate.

**Review by hpk42 — APPROVED** [review]

**Review by hpk42 — CHANGES_REQUESTED** [review]
the internal links need to be fixed (especially between the APIs).  Also it means that the refined structure changes URLs that might point into the webxdc.org site.

**Comment by hpk42** [comment]
however, i don't want to stop your work -- so if the internal links are fixed we can merge and see if any external links really break and if there is a technique to prevent this (a redirection list or something).

**Comment by ralphtheninja** [comment]
@ansuz @hpk42 Is it possible to preview these changes in an easy way online or do I have to run it locally?

**Comment by ansuz** [comment]
> @ansuz @hpk42 Is it possible to preview these changes in an easy way online or do I have to run it locally?

I think it has to be run locally, though I can deploy it somewhere temporarily for easier review

**Comment by ralphtheninja** [comment]
> > @ansuz @hpk42 Is it possible to preview these changes in an easy way online or do I have to run it locally?
> 
> I think it has to be run locally, though I can deploy it somewhere temporarily for easier review

That would be awesome if you have time and energy for that!

**Comment by ansuz** [comment]
this is the current state, including some fixes for broken links that I haven't committed yet: https://demo.cryptography.dog/

**Comment by ralphtheninja** [comment]
I really like the more fine grained menu to the left.

The packaging page looks a bit odd though:

image

**Comment by ralphtheninja** [comment]
I understand that you basically just split the content and didn't change the formatting anything. Maybe we should / could discuss this further after merge. It was just something that caught my eye right now.

**Comment by ansuz** [comment]
> The packaging page looks a bit odd though:

agreed. I think there's a number of things we could probably group together with it, though. Maybe some more information about what should go in `manifest.toml`? That's described in [this section](https://demo.cryptography.dog/spec/index.html?highlight=manifest#the-manifesttoml-file), though that information seems to be written more with platform devs in mind.

Maybe in the future it can contain more tips about how to update? or recommendations for import/export functionality?

**Review by hpk42 — APPROVED** [review]

**Pull request merged**
